
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Lembrete` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Lembrete
 * 
 */
export type LembreteModel = runtime.Types.Result.DefaultSelection<Prisma.$LembretePayload>

export type AggregateLembrete = {
  _count: LembreteCountAggregateOutputType | null
  _avg: LembreteAvgAggregateOutputType | null
  _sum: LembreteSumAggregateOutputType | null
  _min: LembreteMinAggregateOutputType | null
  _max: LembreteMaxAggregateOutputType | null
}

export type LembreteAvgAggregateOutputType = {
  id: number | null
}

export type LembreteSumAggregateOutputType = {
  id: number | null
}

export type LembreteMinAggregateOutputType = {
  id: number | null
  mensagem: string | null
  data_agendada: Date | null
  status: string | null
  criado_em: Date | null
}

export type LembreteMaxAggregateOutputType = {
  id: number | null
  mensagem: string | null
  data_agendada: Date | null
  status: string | null
  criado_em: Date | null
}

export type LembreteCountAggregateOutputType = {
  id: number
  mensagem: number
  data_agendada: number
  status: number
  criado_em: number
  _all: number
}


export type LembreteAvgAggregateInputType = {
  id?: true
}

export type LembreteSumAggregateInputType = {
  id?: true
}

export type LembreteMinAggregateInputType = {
  id?: true
  mensagem?: true
  data_agendada?: true
  status?: true
  criado_em?: true
}

export type LembreteMaxAggregateInputType = {
  id?: true
  mensagem?: true
  data_agendada?: true
  status?: true
  criado_em?: true
}

export type LembreteCountAggregateInputType = {
  id?: true
  mensagem?: true
  data_agendada?: true
  status?: true
  criado_em?: true
  _all?: true
}

export type LembreteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Lembrete to aggregate.
   */
  where?: Prisma.LembreteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Lembretes to fetch.
   */
  orderBy?: Prisma.LembreteOrderByWithRelationInput | Prisma.LembreteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LembreteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Lembretes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Lembretes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Lembretes
  **/
  _count?: true | LembreteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LembreteAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LembreteSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LembreteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LembreteMaxAggregateInputType
}

export type GetLembreteAggregateType<T extends LembreteAggregateArgs> = {
      [P in keyof T & keyof AggregateLembrete]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLembrete[P]>
    : Prisma.GetScalarType<T[P], AggregateLembrete[P]>
}




export type LembreteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LembreteWhereInput
  orderBy?: Prisma.LembreteOrderByWithAggregationInput | Prisma.LembreteOrderByWithAggregationInput[]
  by: Prisma.LembreteScalarFieldEnum[] | Prisma.LembreteScalarFieldEnum
  having?: Prisma.LembreteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LembreteCountAggregateInputType | true
  _avg?: LembreteAvgAggregateInputType
  _sum?: LembreteSumAggregateInputType
  _min?: LembreteMinAggregateInputType
  _max?: LembreteMaxAggregateInputType
}

export type LembreteGroupByOutputType = {
  id: number
  mensagem: string
  data_agendada: Date
  status: string
  criado_em: Date
  _count: LembreteCountAggregateOutputType | null
  _avg: LembreteAvgAggregateOutputType | null
  _sum: LembreteSumAggregateOutputType | null
  _min: LembreteMinAggregateOutputType | null
  _max: LembreteMaxAggregateOutputType | null
}

export type GetLembreteGroupByPayload<T extends LembreteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LembreteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LembreteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LembreteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LembreteGroupByOutputType[P]>
      }
    >
  >



export type LembreteWhereInput = {
  AND?: Prisma.LembreteWhereInput | Prisma.LembreteWhereInput[]
  OR?: Prisma.LembreteWhereInput[]
  NOT?: Prisma.LembreteWhereInput | Prisma.LembreteWhereInput[]
  id?: Prisma.IntFilter<"Lembrete"> | number
  mensagem?: Prisma.StringFilter<"Lembrete"> | string
  data_agendada?: Prisma.DateTimeFilter<"Lembrete"> | Date | string
  status?: Prisma.StringFilter<"Lembrete"> | string
  criado_em?: Prisma.DateTimeFilter<"Lembrete"> | Date | string
}

export type LembreteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  mensagem?: Prisma.SortOrder
  data_agendada?: Prisma.SortOrder
  status?: Prisma.SortOrder
  criado_em?: Prisma.SortOrder
}

export type LembreteWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.LembreteWhereInput | Prisma.LembreteWhereInput[]
  OR?: Prisma.LembreteWhereInput[]
  NOT?: Prisma.LembreteWhereInput | Prisma.LembreteWhereInput[]
  mensagem?: Prisma.StringFilter<"Lembrete"> | string
  data_agendada?: Prisma.DateTimeFilter<"Lembrete"> | Date | string
  status?: Prisma.StringFilter<"Lembrete"> | string
  criado_em?: Prisma.DateTimeFilter<"Lembrete"> | Date | string
}, "id">

export type LembreteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  mensagem?: Prisma.SortOrder
  data_agendada?: Prisma.SortOrder
  status?: Prisma.SortOrder
  criado_em?: Prisma.SortOrder
  _count?: Prisma.LembreteCountOrderByAggregateInput
  _avg?: Prisma.LembreteAvgOrderByAggregateInput
  _max?: Prisma.LembreteMaxOrderByAggregateInput
  _min?: Prisma.LembreteMinOrderByAggregateInput
  _sum?: Prisma.LembreteSumOrderByAggregateInput
}

export type LembreteScalarWhereWithAggregatesInput = {
  AND?: Prisma.LembreteScalarWhereWithAggregatesInput | Prisma.LembreteScalarWhereWithAggregatesInput[]
  OR?: Prisma.LembreteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LembreteScalarWhereWithAggregatesInput | Prisma.LembreteScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Lembrete"> | number
  mensagem?: Prisma.StringWithAggregatesFilter<"Lembrete"> | string
  data_agendada?: Prisma.DateTimeWithAggregatesFilter<"Lembrete"> | Date | string
  status?: Prisma.StringWithAggregatesFilter<"Lembrete"> | string
  criado_em?: Prisma.DateTimeWithAggregatesFilter<"Lembrete"> | Date | string
}

export type LembreteCreateInput = {
  mensagem: string
  data_agendada: Date | string
  status?: string
  criado_em?: Date | string
}

export type LembreteUncheckedCreateInput = {
  id?: number
  mensagem: string
  data_agendada: Date | string
  status?: string
  criado_em?: Date | string
}

export type LembreteUpdateInput = {
  mensagem?: Prisma.StringFieldUpdateOperationsInput | string
  data_agendada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  criado_em?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LembreteUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  mensagem?: Prisma.StringFieldUpdateOperationsInput | string
  data_agendada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  criado_em?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LembreteCreateManyInput = {
  id?: number
  mensagem: string
  data_agendada: Date | string
  status?: string
  criado_em?: Date | string
}

export type LembreteUpdateManyMutationInput = {
  mensagem?: Prisma.StringFieldUpdateOperationsInput | string
  data_agendada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  criado_em?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LembreteUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  mensagem?: Prisma.StringFieldUpdateOperationsInput | string
  data_agendada?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  criado_em?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LembreteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mensagem?: Prisma.SortOrder
  data_agendada?: Prisma.SortOrder
  status?: Prisma.SortOrder
  criado_em?: Prisma.SortOrder
}

export type LembreteAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type LembreteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mensagem?: Prisma.SortOrder
  data_agendada?: Prisma.SortOrder
  status?: Prisma.SortOrder
  criado_em?: Prisma.SortOrder
}

export type LembreteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mensagem?: Prisma.SortOrder
  data_agendada?: Prisma.SortOrder
  status?: Prisma.SortOrder
  criado_em?: Prisma.SortOrder
}

export type LembreteSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type LembreteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mensagem?: boolean
  data_agendada?: boolean
  status?: boolean
  criado_em?: boolean
}, ExtArgs["result"]["lembrete"]>

export type LembreteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mensagem?: boolean
  data_agendada?: boolean
  status?: boolean
  criado_em?: boolean
}, ExtArgs["result"]["lembrete"]>

export type LembreteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mensagem?: boolean
  data_agendada?: boolean
  status?: boolean
  criado_em?: boolean
}, ExtArgs["result"]["lembrete"]>

export type LembreteSelectScalar = {
  id?: boolean
  mensagem?: boolean
  data_agendada?: boolean
  status?: boolean
  criado_em?: boolean
}

export type LembreteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "mensagem" | "data_agendada" | "status" | "criado_em", ExtArgs["result"]["lembrete"]>

export type $LembretePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Lembrete"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    mensagem: string
    data_agendada: Date
    status: string
    criado_em: Date
  }, ExtArgs["result"]["lembrete"]>
  composites: {}
}

export type LembreteGetPayload<S extends boolean | null | undefined | LembreteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LembretePayload, S>

export type LembreteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LembreteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LembreteCountAggregateInputType | true
  }

export interface LembreteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Lembrete'], meta: { name: 'Lembrete' } }
  /**
   * Find zero or one Lembrete that matches the filter.
   * @param {LembreteFindUniqueArgs} args - Arguments to find a Lembrete
   * @example
   * // Get one Lembrete
   * const lembrete = await prisma.lembrete.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LembreteFindUniqueArgs>(args: Prisma.SelectSubset<T, LembreteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LembreteClient<runtime.Types.Result.GetResult<Prisma.$LembretePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Lembrete that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LembreteFindUniqueOrThrowArgs} args - Arguments to find a Lembrete
   * @example
   * // Get one Lembrete
   * const lembrete = await prisma.lembrete.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LembreteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LembreteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LembreteClient<runtime.Types.Result.GetResult<Prisma.$LembretePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Lembrete that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LembreteFindFirstArgs} args - Arguments to find a Lembrete
   * @example
   * // Get one Lembrete
   * const lembrete = await prisma.lembrete.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LembreteFindFirstArgs>(args?: Prisma.SelectSubset<T, LembreteFindFirstArgs<ExtArgs>>): Prisma.Prisma__LembreteClient<runtime.Types.Result.GetResult<Prisma.$LembretePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Lembrete that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LembreteFindFirstOrThrowArgs} args - Arguments to find a Lembrete
   * @example
   * // Get one Lembrete
   * const lembrete = await prisma.lembrete.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LembreteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LembreteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LembreteClient<runtime.Types.Result.GetResult<Prisma.$LembretePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Lembretes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LembreteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Lembretes
   * const lembretes = await prisma.lembrete.findMany()
   * 
   * // Get first 10 Lembretes
   * const lembretes = await prisma.lembrete.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const lembreteWithIdOnly = await prisma.lembrete.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LembreteFindManyArgs>(args?: Prisma.SelectSubset<T, LembreteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LembretePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Lembrete.
   * @param {LembreteCreateArgs} args - Arguments to create a Lembrete.
   * @example
   * // Create one Lembrete
   * const Lembrete = await prisma.lembrete.create({
   *   data: {
   *     // ... data to create a Lembrete
   *   }
   * })
   * 
   */
  create<T extends LembreteCreateArgs>(args: Prisma.SelectSubset<T, LembreteCreateArgs<ExtArgs>>): Prisma.Prisma__LembreteClient<runtime.Types.Result.GetResult<Prisma.$LembretePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Lembretes.
   * @param {LembreteCreateManyArgs} args - Arguments to create many Lembretes.
   * @example
   * // Create many Lembretes
   * const lembrete = await prisma.lembrete.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LembreteCreateManyArgs>(args?: Prisma.SelectSubset<T, LembreteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Lembretes and returns the data saved in the database.
   * @param {LembreteCreateManyAndReturnArgs} args - Arguments to create many Lembretes.
   * @example
   * // Create many Lembretes
   * const lembrete = await prisma.lembrete.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Lembretes and only return the `id`
   * const lembreteWithIdOnly = await prisma.lembrete.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LembreteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LembreteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LembretePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Lembrete.
   * @param {LembreteDeleteArgs} args - Arguments to delete one Lembrete.
   * @example
   * // Delete one Lembrete
   * const Lembrete = await prisma.lembrete.delete({
   *   where: {
   *     // ... filter to delete one Lembrete
   *   }
   * })
   * 
   */
  delete<T extends LembreteDeleteArgs>(args: Prisma.SelectSubset<T, LembreteDeleteArgs<ExtArgs>>): Prisma.Prisma__LembreteClient<runtime.Types.Result.GetResult<Prisma.$LembretePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Lembrete.
   * @param {LembreteUpdateArgs} args - Arguments to update one Lembrete.
   * @example
   * // Update one Lembrete
   * const lembrete = await prisma.lembrete.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LembreteUpdateArgs>(args: Prisma.SelectSubset<T, LembreteUpdateArgs<ExtArgs>>): Prisma.Prisma__LembreteClient<runtime.Types.Result.GetResult<Prisma.$LembretePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Lembretes.
   * @param {LembreteDeleteManyArgs} args - Arguments to filter Lembretes to delete.
   * @example
   * // Delete a few Lembretes
   * const { count } = await prisma.lembrete.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LembreteDeleteManyArgs>(args?: Prisma.SelectSubset<T, LembreteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Lembretes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LembreteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Lembretes
   * const lembrete = await prisma.lembrete.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LembreteUpdateManyArgs>(args: Prisma.SelectSubset<T, LembreteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Lembretes and returns the data updated in the database.
   * @param {LembreteUpdateManyAndReturnArgs} args - Arguments to update many Lembretes.
   * @example
   * // Update many Lembretes
   * const lembrete = await prisma.lembrete.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Lembretes and only return the `id`
   * const lembreteWithIdOnly = await prisma.lembrete.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LembreteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LembreteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LembretePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Lembrete.
   * @param {LembreteUpsertArgs} args - Arguments to update or create a Lembrete.
   * @example
   * // Update or create a Lembrete
   * const lembrete = await prisma.lembrete.upsert({
   *   create: {
   *     // ... data to create a Lembrete
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Lembrete we want to update
   *   }
   * })
   */
  upsert<T extends LembreteUpsertArgs>(args: Prisma.SelectSubset<T, LembreteUpsertArgs<ExtArgs>>): Prisma.Prisma__LembreteClient<runtime.Types.Result.GetResult<Prisma.$LembretePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Lembretes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LembreteCountArgs} args - Arguments to filter Lembretes to count.
   * @example
   * // Count the number of Lembretes
   * const count = await prisma.lembrete.count({
   *   where: {
   *     // ... the filter for the Lembretes we want to count
   *   }
   * })
  **/
  count<T extends LembreteCountArgs>(
    args?: Prisma.Subset<T, LembreteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LembreteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Lembrete.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LembreteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LembreteAggregateArgs>(args: Prisma.Subset<T, LembreteAggregateArgs>): Prisma.PrismaPromise<GetLembreteAggregateType<T>>

  /**
   * Group by Lembrete.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LembreteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LembreteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LembreteGroupByArgs['orderBy'] }
      : { orderBy?: LembreteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LembreteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLembreteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Lembrete model
 */
readonly fields: LembreteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Lembrete.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LembreteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Lembrete model
 */
export interface LembreteFieldRefs {
  readonly id: Prisma.FieldRef<"Lembrete", 'Int'>
  readonly mensagem: Prisma.FieldRef<"Lembrete", 'String'>
  readonly data_agendada: Prisma.FieldRef<"Lembrete", 'DateTime'>
  readonly status: Prisma.FieldRef<"Lembrete", 'String'>
  readonly criado_em: Prisma.FieldRef<"Lembrete", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Lembrete findUnique
 */
export type LembreteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lembrete
   */
  select?: Prisma.LembreteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lembrete
   */
  omit?: Prisma.LembreteOmit<ExtArgs> | null
  /**
   * Filter, which Lembrete to fetch.
   */
  where: Prisma.LembreteWhereUniqueInput
}

/**
 * Lembrete findUniqueOrThrow
 */
export type LembreteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lembrete
   */
  select?: Prisma.LembreteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lembrete
   */
  omit?: Prisma.LembreteOmit<ExtArgs> | null
  /**
   * Filter, which Lembrete to fetch.
   */
  where: Prisma.LembreteWhereUniqueInput
}

/**
 * Lembrete findFirst
 */
export type LembreteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lembrete
   */
  select?: Prisma.LembreteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lembrete
   */
  omit?: Prisma.LembreteOmit<ExtArgs> | null
  /**
   * Filter, which Lembrete to fetch.
   */
  where?: Prisma.LembreteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Lembretes to fetch.
   */
  orderBy?: Prisma.LembreteOrderByWithRelationInput | Prisma.LembreteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Lembretes.
   */
  cursor?: Prisma.LembreteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Lembretes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Lembretes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Lembretes.
   */
  distinct?: Prisma.LembreteScalarFieldEnum | Prisma.LembreteScalarFieldEnum[]
}

/**
 * Lembrete findFirstOrThrow
 */
export type LembreteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lembrete
   */
  select?: Prisma.LembreteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lembrete
   */
  omit?: Prisma.LembreteOmit<ExtArgs> | null
  /**
   * Filter, which Lembrete to fetch.
   */
  where?: Prisma.LembreteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Lembretes to fetch.
   */
  orderBy?: Prisma.LembreteOrderByWithRelationInput | Prisma.LembreteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Lembretes.
   */
  cursor?: Prisma.LembreteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Lembretes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Lembretes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Lembretes.
   */
  distinct?: Prisma.LembreteScalarFieldEnum | Prisma.LembreteScalarFieldEnum[]
}

/**
 * Lembrete findMany
 */
export type LembreteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lembrete
   */
  select?: Prisma.LembreteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lembrete
   */
  omit?: Prisma.LembreteOmit<ExtArgs> | null
  /**
   * Filter, which Lembretes to fetch.
   */
  where?: Prisma.LembreteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Lembretes to fetch.
   */
  orderBy?: Prisma.LembreteOrderByWithRelationInput | Prisma.LembreteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Lembretes.
   */
  cursor?: Prisma.LembreteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Lembretes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Lembretes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Lembretes.
   */
  distinct?: Prisma.LembreteScalarFieldEnum | Prisma.LembreteScalarFieldEnum[]
}

/**
 * Lembrete create
 */
export type LembreteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lembrete
   */
  select?: Prisma.LembreteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lembrete
   */
  omit?: Prisma.LembreteOmit<ExtArgs> | null
  /**
   * The data needed to create a Lembrete.
   */
  data: Prisma.XOR<Prisma.LembreteCreateInput, Prisma.LembreteUncheckedCreateInput>
}

/**
 * Lembrete createMany
 */
export type LembreteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Lembretes.
   */
  data: Prisma.LembreteCreateManyInput | Prisma.LembreteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Lembrete createManyAndReturn
 */
export type LembreteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lembrete
   */
  select?: Prisma.LembreteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Lembrete
   */
  omit?: Prisma.LembreteOmit<ExtArgs> | null
  /**
   * The data used to create many Lembretes.
   */
  data: Prisma.LembreteCreateManyInput | Prisma.LembreteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Lembrete update
 */
export type LembreteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lembrete
   */
  select?: Prisma.LembreteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lembrete
   */
  omit?: Prisma.LembreteOmit<ExtArgs> | null
  /**
   * The data needed to update a Lembrete.
   */
  data: Prisma.XOR<Prisma.LembreteUpdateInput, Prisma.LembreteUncheckedUpdateInput>
  /**
   * Choose, which Lembrete to update.
   */
  where: Prisma.LembreteWhereUniqueInput
}

/**
 * Lembrete updateMany
 */
export type LembreteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Lembretes.
   */
  data: Prisma.XOR<Prisma.LembreteUpdateManyMutationInput, Prisma.LembreteUncheckedUpdateManyInput>
  /**
   * Filter which Lembretes to update
   */
  where?: Prisma.LembreteWhereInput
  /**
   * Limit how many Lembretes to update.
   */
  limit?: number
}

/**
 * Lembrete updateManyAndReturn
 */
export type LembreteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lembrete
   */
  select?: Prisma.LembreteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Lembrete
   */
  omit?: Prisma.LembreteOmit<ExtArgs> | null
  /**
   * The data used to update Lembretes.
   */
  data: Prisma.XOR<Prisma.LembreteUpdateManyMutationInput, Prisma.LembreteUncheckedUpdateManyInput>
  /**
   * Filter which Lembretes to update
   */
  where?: Prisma.LembreteWhereInput
  /**
   * Limit how many Lembretes to update.
   */
  limit?: number
}

/**
 * Lembrete upsert
 */
export type LembreteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lembrete
   */
  select?: Prisma.LembreteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lembrete
   */
  omit?: Prisma.LembreteOmit<ExtArgs> | null
  /**
   * The filter to search for the Lembrete to update in case it exists.
   */
  where: Prisma.LembreteWhereUniqueInput
  /**
   * In case the Lembrete found by the `where` argument doesn't exist, create a new Lembrete with this data.
   */
  create: Prisma.XOR<Prisma.LembreteCreateInput, Prisma.LembreteUncheckedCreateInput>
  /**
   * In case the Lembrete was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LembreteUpdateInput, Prisma.LembreteUncheckedUpdateInput>
}

/**
 * Lembrete delete
 */
export type LembreteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lembrete
   */
  select?: Prisma.LembreteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lembrete
   */
  omit?: Prisma.LembreteOmit<ExtArgs> | null
  /**
   * Filter which Lembrete to delete.
   */
  where: Prisma.LembreteWhereUniqueInput
}

/**
 * Lembrete deleteMany
 */
export type LembreteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Lembretes to delete
   */
  where?: Prisma.LembreteWhereInput
  /**
   * Limit how many Lembretes to delete.
   */
  limit?: number
}

/**
 * Lembrete without action
 */
export type LembreteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lembrete
   */
  select?: Prisma.LembreteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lembrete
   */
  omit?: Prisma.LembreteOmit<ExtArgs> | null
}
